// M/2026/05/14/9 (M/83) — Flat config ESLint 9+ pour ocre-immo.
// Cible : extraction JS de index.html (monolithe React via CDN).
// Mode minimal sans build step. Detection no-undef (catch ReferenceError comme
// le bug setClients M/2026/05/14/4) + warnings no-unused-vars.

module.exports = [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        React: "readonly",
        ReactDOM: "readonly",
        fetch: "readonly",
        window: "readonly",
        document: "readonly",
        crypto: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        Headers: "readonly",
        Response: "readonly",
        Request: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Symbol: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        Math: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        atob: "readonly",
        btoa: "readonly",
        caches: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        Notification: "readonly",
        indexedDB: "readonly",
        AbortController: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        Element: "readonly",
        Node: "readonly",
        HTMLElement: "readonly",
        process: "readonly",
        module: "readonly",
        exports: "readonly",
        require: "readonly",
        // React conventions custom
        useState: "readonly",
        useEffect: "readonly",
        useRef: "readonly",
        useCallback: "readonly",
        useMemo: "readonly",
        // Browser APIs additionnelles (detectees au lint M/2026/05/14/9 initial)
        MediaRecorder: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLAudioElement: "readonly",
        SpeechRecognition: "readonly",
        webkitSpeechRecognition: "readonly",
        WebSocket: "readonly",
        EventSource: "readonly",
        BroadcastChannel: "readonly",
        getComputedStyle: "readonly",
        DOMParser: "readonly",
        Worker: "readonly",
        SharedWorker: "readonly",
        ServiceWorker: "readonly",
      },
    },
    // Ignorer les directives eslint-disable inline qui referencent des plugins
    // non installes (react-hooks/exhaustive-deps). On ne lint pas les hooks, le
    // monolithe est trop bruyant pour ce niveau de check.
    linterOptions: {
      noInlineConfig: false,
      reportUnusedDisableDirectives: "off",
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
      "no-console": "off",
    },
  },
];
