-- M/2026/05/06/83.1 — Tables backend modele matching anonyme entre agents pactes.
-- Idempotent (CREATE TABLE IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS agents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(190) NOT NULL UNIQUE,
    prenom VARCHAR(100) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    tel VARCHAR(30) NULL,
    whatsapp VARCHAR(30) NULL,
    telegram_chat_id VARCHAR(50) NULL,
    siren VARCHAR(20) NULL,
    siret VARCHAR(20) NULL,
    carte_pro VARCHAR(50) NULL,
    fnaim VARCHAR(50) NULL,
    agence VARCHAR(150) NULL,
    adresse VARCHAR(255) NULL,
    ville VARCHAR(100) NULL,
    cp VARCHAR(10) NULL,
    pays VARCHAR(60) NULL DEFAULT 'France',
    role ENUM('super_admin','agent','agent_testeur') NOT NULL DEFAULT 'agent',
    verified_at TIMESTAMP NULL,
    verified_by INT NULL,
    channels_enabled JSON NULL COMMENT 'JSON {"telegram":true,"email":true,"whatsapp":false}',
    sensibility_preset ENUM('strict','equilibre','large','tres_large') NOT NULL DEFAULT 'equilibre',
    sensibility_custom JSON NULL COMMENT 'JSON {"prix_pct":15,"surface_pct":25,"rayon_km":5,"score_min":65}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_email (email),
    INDEX idx_role (role),
    INDEX idx_ville (ville)
);

CREATE TABLE IF NOT EXISTS agent_pacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    agent_a_id INT NOT NULL,
    agent_b_id INT NOT NULL,
    invited_by INT NOT NULL COMMENT 'agent_a ou agent_b qui a initie',
    invitation_token VARCHAR(255) NULL,
    invitation_email VARCHAR(190) NULL,
    invitation_sent_at TIMESTAMP NULL,
    invitation_expires_at TIMESTAMP NULL,
    status ENUM('pending','active','revoked','expired') NOT NULL DEFAULT 'pending',
    signed_a_at TIMESTAMP NULL,
    signed_b_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    revoked_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_a_id) REFERENCES agents(id) ON DELETE CASCADE,
    FOREIGN KEY (agent_b_id) REFERENCES agents(id) ON DELETE CASCADE,
    UNIQUE KEY uk_pact (agent_a_id, agent_b_id),
    INDEX idx_status (status),
    INDEX idx_token (invitation_token)
);

CREATE TABLE IF NOT EXISTS match_proposals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id INT NOT NULL COMMENT 'agent destinataire de la proposition',
    my_client_id INT(10) UNSIGNED NOT NULL COMMENT 'mon dossier (cote agent_id)',
    their_agent_id INT NULL COMMENT 'NULL si source=external',
    their_client_id INT(10) UNSIGNED NULL COMMENT 'NULL si source=external',
    external_url VARCHAR(500) NULL,
    external_data JSON NULL COMMENT 'snapshot JSON de l annonce externe',
    score DECIMAL(4,3) NOT NULL COMMENT '0.000 a 1.000',
    score_breakdown JSON NULL COMMENT 'JSON detail des criteres matches',
    source ENUM('ocre','external') NOT NULL,
    status ENUM('proposed','viewed','connection_requested','accepted','dismissed','expired') NOT NULL DEFAULT 'proposed',
    scan_run_id VARCHAR(40) NULL COMMENT 'identifiant du run de scan (cron ou manuel)',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    viewed_at TIMESTAMP NULL,
    actioned_at TIMESTAMP NULL,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    FOREIGN KEY (my_client_id) REFERENCES clients(id) ON DELETE CASCADE,
    FOREIGN KEY (their_agent_id) REFERENCES agents(id) ON DELETE SET NULL,
    FOREIGN KEY (their_client_id) REFERENCES clients(id) ON DELETE SET NULL,
    INDEX idx_agent_status (agent_id, status),
    INDEX idx_source (source),
    INDEX idx_scan_run (scan_run_id),
    INDEX idx_created (created_at DESC)
);

CREATE TABLE IF NOT EXISTS external_listings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    source_url VARCHAR(500) NOT NULL,
    source_site VARCHAR(100) NOT NULL COMMENT 'avito, mubawab, sarouty, etc.',
    region VARCHAR(100) NOT NULL,
    type_bien VARCHAR(60) NOT NULL,
    surface_m2 DECIMAL(8,2) NULL,
    prix DECIMAL(15,2) NULL,
    devise VARCHAR(10) NULL,
    titre VARCHAR(300) NULL,
    description TEXT NULL,
    photos JSON NULL,
    coords_lat DECIMAL(10,7) NULL,
    coords_lng DECIMAL(10,7) NULL,
    scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE KEY uk_url (source_url(190)),
    INDEX idx_region_type (region, type_bien),
    INDEX idx_active (is_active),
    INDEX idx_prix (prix)
);

CREATE TABLE IF NOT EXISTS notify_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id INT NOT NULL,
    channel ENUM('telegram','email','whatsapp') NOT NULL,
    type VARCHAR(60) NOT NULL COMMENT 'matches_daily, scan_result, pact_invitation, etc.',
    recipient VARCHAR(255) NOT NULL,
    payload JSON NULL,
    status ENUM('queued','sent','delivered','failed','bounced') NOT NULL DEFAULT 'queued',
    error_message VARCHAR(500) NULL,
    sent_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    INDEX idx_agent_channel (agent_id, channel),
    INDEX idx_status (status),
    INDEX idx_created (created_at DESC)
);
